[tools]
# =================================================================================================
# Project Tools
# =================================================================================================
go = "1.26.3"
golangci-lint = "2.12.2"
"aqua:goreleaser/goreleaser" = "2.15.4"

# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"shellcheck" = "0.11"
"ubi:caarlos0/svu" = "latest"
