---
# Production configuration - uses pre-built images from GHCR
# For single-instance deployments, you can remove the 'redis' service and
# remove the 'depends_on' and 'environment' sections from the backend service
services:
  backend:
    image: ghcr.io/mirceanton/teleprompter-backend:latest
    ports: [ "8001:8001" ]
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8001/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/mirceanton/teleprompter-frontend:latest
    ports: ["8000:80"]
    restart: unless-stopped
    volumes:
      - ./frontend/public/config.json:/usr/share/nginx/html/config.json:ro

  redis:
    image: docker.io/redis:8.2.1-alpine
    ports: ["6379:6379"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
