services:
  # Unified Teleprompter Application (Backend + Frontend SSR)
  teleprompter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # WebSocket URL for frontend to backend connection
      - TELEPROMPTER_WS_URL=${TELEPROMPTER_WS_URL:-}
      # UI subpath for running on a subpath
      - TELEPROMPTER_UI_SUBPATH=${TELEPROMPTER_UI_SUBPATH:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: teleprompter-network
