services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    networks:
      - teleprompter-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8001/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Unified Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      # Mount custom config.json if needed
      # - ./config.json:/usr/share/nginx/html/config.json:ro
    networks:
      - teleprompter-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  teleprompter-network:
    driver: bridge
