---
name: Build and Push Docker Images
permissions:
  contents: read
  packages: write

on:
  pull_request:
    paths:
      - 'services/**'
  release: { types: [ created ] }
  workflow_dispatch:
    inputs:
      push:
        description: 'Push the Docker images to the registry'
        type: boolean
        default: false
      service:
        description: 'Specific service to build (leave empty to build all services)'
        type: string
        required: false

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Generate matrix from services directory
        uses: mirceanton/action-folder-matrix@v2.0.0
        id: set-matrix
        with:
          path: 'services'
          filter: ${{ github.event.inputs.service || '' }}
          changed-only: ${{ github.event_name == 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Metadata
        uses: docker/metadata-action@v5.8.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.folder }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./services/${{ matrix.folder }}
          push: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
